### ISSUE TITLE
Nanodegree forums are not accessible from classrooms

### ISSUE THREAD

**Issue by vzhz** [udacity/fend-issue-reports#4]
When I click on the following
>Have questions? Head to the forums for discussion with the Udacity Community.

I am brought to [this error page](https://discussions.udacity.com/c/nd001-front-end-broadcast) which says 
>Oops! That page doesn't exist or is private.

**Comment by hbkwong** [comment]
Hi vzhz, the classroom had since been updated with links to Knowledge and Student Hub!
